
name: 'Create CSS assets from Figma'
description: 'Produces a set of CSS assets from the Figma plugin tokens file'
inputs:
  tokens-json:
    description: 'String of JSON representing the Figma tokens'
    required: true
  token-types:
    description: 'Comma-separated set of css, less, sccs, ios'
    required: true
  results-dir:
    description: 'Host location for generated assets'
    required: true  

runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{ inputs.tokens-json }}
    - ${{ inputs.token-types }}
    - ${{ inputs.results-dir }}    
